version: "3.1"

services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - whiteboard

  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - whiteboard

networks:
  whiteboard:
    driver: bridge
